name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - uses: nrwl/nx-set-shas@v4

      - name: Format Check
        if: always()
        run: pnpm run format:check

      - name: Lint
        if: always()
        run: pnpm exec nx affected -t lint --verbose

      - name: Test
        if: always()
        run: pnpm exec nx affected -t test --verbose --configuration=ci

      - name: E2E Test
        if: always()
        run: pnpm exec nx affected -t test:e2e --verbose

      - name: Coverage
        if: always()
        run: pnpm exec nx run fastify-app:test --configuration=coverage

      - name: Build
        if: always()
        run: pnpm exec nx affected -t build --verbose

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/
          retention-days: 7
